# Elasticsearch datasource for North Cloud (classified content, search)
# Used by pipeline dashboard for classifier observability panels

apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    uid: elasticsearch
    url: http://elasticsearch:9200
    isDefault: false
    editable: true
    # Default index for all queries (classified content indexes)
    database: '*_classified_content'
    jsonData:
      esVersion: '9.0.0'
      logMessageField: msg
      logLevelField: level
      # Classified content uses crawled_at; @timestamp is not in the mapping
      timeField: crawled_at
