version: '3'

tasks:
  list:
    desc: "List all sources"
    cmds:
      - go run main.go sources list
    ignore_error: true

  add:
    desc: Add a new source
    cmds:
      - go run main.go sources add

  remove:
    desc: Remove a source
    cmds:
      - go run main.go sources remove


